services:
  centos_main:
    container_name: centos_main
    build: ./docker
    command: /sbin/init
    volumes:
      - ./script:/script
    privileged: true
    networks:
      test_network:
        ipv4_address: 172.30.0.2
  centos_sub:
    container_name: centos_sub
    build: ./docker
    command: /sbin/init
    privileged: true
    networks:
      test_network:
        ipv4_address: 172.30.0.4

networks:
  test_network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24