services:
  centos_main:
    container_name: centos_main
    build: ./docker
    volumes:
      - ./script:/script
    networks:
      test_network:
        ipv4_address: 172.30.0.2

  centos_sub:
    container_name: centos_sub
    build: ./docker
    # ports:
    #   - "5432:5432"
    networks:
      test_network:
        ipv4_address: 172.30.0.4

networks:
  test_network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24